name: Python package and test

on:
  push:
  pull_request:

jobs:
  checkout-test:
    name: Checkout and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            ENV_FILE: install/envs/mac.yml
          - os: ubuntu-latest
            ENV_FILE: install/envs/ubuntu.yml
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create python 3.7 conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          mamba-version: "*"
          activate-environment: donkey
          environment-file: ${{matrix.ENV_FILE}}
          auto-activate-base: false
          channels: default, conda-forge, pytorch
          channel-priority: true
      - name: Conda info and list
        run: |
          echo Environment file ${{matrix.ENV_FILE}}
          conda info
          conda list
      - name: Install donkey
        run: pip install -e .[pc]
      - name: Run tests
        run: pytest
